// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCinema.Models;

#nullable disable

namespace ProjetoCinema.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoCinema.Models.Bomboniere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BomboniereId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescricaoProduto");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeProduto");

                    b.Property<string>("PrecoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PrecoProduto");

                    b.Property<string>("TamanhoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TamanhoProduto");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Bomboniere");
                });

            modelBuilder.Entity("ProjetoCinema.Models.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CadastroId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClienteNome");

                    b.Property<string>("Entrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Entrada");

                    b.Property<string>("EscolhaFilme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EscolhaFilme");

                    b.Property<DateTime>("HrSessao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HrSessao");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lugar");

                    b.Property<string>("Pedidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pedidos");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("ProjetoCinema.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaNome");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ProjetoCinema.Models.EspecialHorror", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HorrorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classificacao")
                        .HasColumnType("int")
                        .HasColumnName("Classificacao");

                    b.Property<string>("Filmes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Filmes");

                    b.Property<DateTime>("HrSesssao")
                        .HasColumnType("datetime2")
                        .HasColumnName("HrSesssao");

                    b.HasKey("Id");

                    b.ToTable("EspecialHorror");
                });

            modelBuilder.Entity("ProjetoCinema.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FilmesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilmeNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FilmeNome");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("Idade");

                    b.Property<DateTime>("SesssaoHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("SesssaoHora");

                    b.HasKey("Id");

                    b.ToTable("Filme");
                });

            modelBuilder.Entity("ProjetoCinema.Models.Bomboniere", b =>
                {
                    b.HasOne("ProjetoCinema.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
